repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: autopep8-wrapper
      args:
        - --in-place
        - --max-line-length=99
    - id: flake8
      args:
        - --max-line-length=99
    - id: check-ast
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: trailing-whitespace
    - id: pretty-format-json
      args:
        - --autofix
# We run pylint from local env, to ensure modules can be found
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: python -m pylint.__main__
      language: system
      types: [python]
      args:
        - --include-naming-hint=yes
        - --max-args=15
        - --max-returns=10
        - --ignore-imports=yes
        - --disable=attribute-defined-outside-init
        - --disable=broad-except
        - --disable=duplicate-code
        - --disable=missing-docstring
        # https://github.com/PyCQA/pylint/issues/2440
        - --disable=not-an-iterable
        - --disable=not-async-context-manager
        - --disable=possibly-unused-variable
        - --disable=protected-access
        - --disable=too-few-public-methods
        - --disable=too-many-instance-attributes
        - --disable=too-many-lines
        - --disable=too-many-locals
        - --disable=too-many-public-methods
        - --disable=too-many-statements
        - --disable=try-except-raise
