FROM minio/minio:RELEASE.2018-10-25T01-27-03Z

RUN \
    apk add --no-cache \
        openssl=1.0.2p-r0
COPY minio-entrypoint.sh /
RUN mkdir -p /test-data/my-bucket

ENTRYPOINT ["/minio-entrypoint.sh"]
CMD ["server", "/test-data"]
