FROM minio/minio:RELEASE.2018-11-22T02-51-56Z

RUN \
    apk add --no-cache \
        openssl=1.0.2t-r0
COPY minio-entrypoint.sh /
RUN mkdir -p /test-data/my-bucket
RUN mkdir -p /test-data/my-bucket-acme

ENTRYPOINT ["/minio-entrypoint.sh"]
CMD ["server", "/test-data"]
